"use client";

import { ThemeProvider } from "@/providers/themeProvider/ThemeProvider";
import ReactLenis from "lenis/react";
import ContactCenter from '@/components/sections/contact/ContactCenter';
import FaqDouble from '@/components/sections/faq/FaqDouble';
import FeatureCardTwentyFive from '@/components/sections/feature/FeatureCardTwentyFive';
import FooterBaseReveal from '@/components/sections/footer/FooterBaseReveal';
import HeroOverlay from '@/components/sections/hero/HeroOverlay';
import MetricCardFourteen from '@/components/sections/metrics/MetricCardFourteen';
import NavbarLayoutFloatingOverlay from '@/components/navbar/NavbarLayoutFloatingOverlay/NavbarLayoutFloatingOverlay';
import PricingCardEight from '@/components/sections/pricing/PricingCardEight';
import SplitAbout from '@/components/sections/about/SplitAbout';
import TestimonialCardSixteen from '@/components/sections/testimonial/TestimonialCardSixteen';
import { BookOpen, Lightbulb, ShieldCheck } from "lucide-react";

export default function LandingPage() {
  return (
    <ThemeProvider
        defaultButtonVariant="icon-arrow"
        defaultTextAnimation="entrance-slide"
        borderRadius="soft"
        contentWidth="mediumLarge"
        sizing="mediumLargeSizeMediumTitles"
        background="aurora"
        cardStyle="outline"
        primaryButtonStyle="flat"
        secondaryButtonStyle="glass"
        headingFontWeight="medium"
    >
      <ReactLenis root>
  <div id="nav" data-section="nav">
      <NavbarLayoutFloatingOverlay
      navItems={[
        {
          name: "Home",
          id: "hero",
        },
        {
          name: "About",
          id: "about",
        },
        {
          name: "Education",
          id: "education",
        },
        {
          name: "Pricing",
          id: "pricing",
        },
        {
          name: "Contact",
          id: "contact",
        },
      ]}
      brandName="ADG Trading Center"
    />
  </div>

  <div id="hero" data-section="hero">
      <HeroOverlay
      title="Learn Trading the Right Way"
      description="Start your trading journey with ADG Trading Center. Learn, practice, and grow with professional guidance and funded-style demo accounts."
      buttons={[
        {
          text: "Start Trading",
          href: "#pricing",
        },
        {
          text: "View Demo Accounts",
          href: "#pricing",
        },
      ]}
      imageSrc="http://img.b2bpic.net/free-photo/trading-stock-stock-market-business-graph-trading-investment-broker-stock-exchange-market_169016-66723.jpg"
      showDimOverlay={true}
      avatars={[
        {
          src: "http://img.b2bpic.net/free-photo/ai-powered-device-concept_23-2151924116.jpg",
          alt: "Ai powered device concept",
        },
        {
          src: "http://img.b2bpic.net/free-photo/abstract-green-background-light-shadows-generative-ai_169016-30460.jpg",
          alt: "Abstract green background light and shadows generative AI",
        },
        {
          src: "http://img.b2bpic.net/free-photo/trading-stock-stock-market-business-graph-trading-investment-broker-stock-exchange-market_169016-66520.jpg",
          alt: "Trading stock stock market business graph trading investment broker stock exchange market",
        },
        {
          src: "http://img.b2bpic.net/free-photo/glowing-computer-monitor-displays-financial-figures-trading-generated-by-ai_188544-22628.jpg",
          alt: "Glowing computer monitor displays financial figures for trading generated by AI",
        },
        {
          src: "http://img.b2bpic.net/free-photo/front-view-with-businessman-modern-office-blue-lightan-moon-light_482257-32826.jpg",
          alt: "Front view with a businessman in a modern office. Blue lightan and moon light",
        },
      ]}
      avatarText="Join 1,200+ successful traders"
    />
  </div>

  <div id="about" data-section="about">
      <SplitAbout
      textboxLayout="split"
      useInvertedBackground={true}
      title="Commitment to Excellence"
      description="ADG Trading Center provides a structured environment for aspiring traders to refine their skills. We emphasize discipline, risk management, and sound psychological preparation through professional-grade educational content and demo testing environments."
      bulletPoints={[
        {
          title: "Expert Education",
          description: "Master market mechanics and analysis.",
        },
        {
          title: "Risk Focus",
          description: "Learn to preserve capital with discipline.",
        },
        {
          title: "Guided Growth",
          description: "Mentorship programs for serious traders.",
        },
      ]}
      imageSrc="http://img.b2bpic.net/free-photo/startup-team-review-financial-reports-performance-metrics-laptop_482257-90887.jpg"
    />
  </div>

  <div id="education" data-section="education">
      <FeatureCardTwentyFive
      animationType="slide-up"
      textboxLayout="default"
      useInvertedBackground={false}
      features={[
        {
          title: "Forex Fundamentals",
          description: "Understand pairs, leverage, and margin.",
          icon: BookOpen,
          mediaItems: [
            {
              imageSrc: "http://img.b2bpic.net/free-photo/gold-bull-backgrounds-graphics-elements-related-financial-sector_23-2151807637.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/menu-circle-button-right-side-with-white-background_187299-40075.jpg",
            },
          ],
          imageSrc: "http://img.b2bpic.net/free-photo/trading-stock-stock-market-business-graph-trading-investment-broker-stock-exchange-market_169016-66723.jpg",
          imageAlt: "forex education icon gold",
        },
        {
          title: "Risk Management",
          description: "Protecting your equity is the priority.",
          icon: ShieldCheck,
          mediaItems: [
            {
              imageSrc: "http://img.b2bpic.net/free-vector/pack-golden-shields-flat-design_23-2147611013.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/economic-crisis-bocks_23-2148542037.jpg",
            },
          ],
          imageSrc: "http://img.b2bpic.net/free-photo/startup-team-review-financial-reports-performance-metrics-laptop_482257-90887.jpg",
          imageAlt: "forex education icon gold",
        },
        {
          title: "Psychology",
          description: "Mastering the mental aspect of markets.",
          icon: Lightbulb,
          mediaItems: [
            {
              imageSrc: "http://img.b2bpic.net/free-photo/still-life-illustrating-ethics-concept_23-2149412239.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/charts-finance-text-white-background_23-2148305954.jpg",
            },
          ],
          imageSrc: "http://img.b2bpic.net/free-photo/hispanic-man-working-office-night-smiling-cheerful-showing-pointing-with-fingers-teeth-mouth-dental-health-concept_839833-28090.jpg",
          imageAlt: "forex education icon gold",
        },
      ]}
      title="Comprehensive Education"
      description="Our curriculum covers every aspect of the trading lifecycle."
    />
  </div>

  <div id="metrics" data-section="metrics">
      <MetricCardFourteen
      useInvertedBackground={true}
      title="Success in Numbers"
      tag="Our Impact"
      metrics={[
        {
          id: "m1",
          value: "1,200+",
          description: "Traders Trained",
        },
        {
          id: "m2",
          value: "95%",
          description: "Success Rate",
        },
        {
          id: "m3",
          value: "24/7",
          description: "Support Availability",
        },
      ]}
      metricsAnimation="slide-up"
    />
  </div>

  <div id="pricing" data-section="pricing">
      <PricingCardEight
      animationType="slide-up"
      textboxLayout="default"
      useInvertedBackground={false}
      plans={[
        {
          id: "p1",
          badge: "Starter",
          price: "$25",
          subtitle: "$10,000 Account",
          features: [
            "Access to dashboard",
            "Market reports",
          ],
          buttons: [
            {
              text: "Buy Now",
              href: "#contact",
            },
          ],
        },
        {
          id: "p2",
          badge: "Most Popular",
          price: "$65",
          subtitle: "$55,000 Account",
          features: [
            "Full access",
            "Advanced course",
            "Priority support",
          ],
          buttons: [
            {
              text: "Buy Now",
              href: "#contact",
            },
          ],
        },
        {
          id: "p3",
          badge: "Best Value",
          price: "$85",
          subtitle: "$75,000 Account",
          features: [
            "Everything in Pro",
            "One-on-one call",
          ],
          buttons: [
            {
              text: "Buy Now",
              href: "#contact",
            },
          ],
        },
      ]}
      title="Demo Account Plans"
      description="Choose the account size that fits your learning journey."
    />
  </div>

  <div id="testimonials" data-section="testimonials">
      <TestimonialCardSixteen
      animationType="slide-up"
      textboxLayout="split"
      useInvertedBackground={true}
      testimonials={[
        {
          id: "t1",
          name: "Mark D.",
          role: "Full-time Trader",
          company: "Student",
          rating: 5,
          imageSrc: "http://img.b2bpic.net/free-photo/hispanic-man-working-office-night-smiling-cheerful-showing-pointing-with-fingers-teeth-mouth-dental-health-concept_839833-28090.jpg",
        },
        {
          id: "t2",
          name: "Sarah P.",
          role: "Equity Trader",
          company: "Student",
          rating: 5,
          imageSrc: "http://img.b2bpic.net/free-photo/woman-standing-cork-board_329181-15260.jpg",
        },
        {
          id: "t3",
          name: "John R.",
          role: "Swing Trader",
          company: "Student",
          rating: 5,
          imageSrc: "http://img.b2bpic.net/free-photo/project-manager-examining-performance-metrics-ensure-global-business-success_482257-104719.jpg",
        },
        {
          id: "t4",
          name: "Emily C.",
          role: "FX Scalper",
          company: "Student",
          rating: 5,
          imageSrc: "http://img.b2bpic.net/free-photo/authentic-small-youthful-marketing-agency_23-2150167333.jpg",
        },
        {
          id: "t5",
          name: "David L.",
          role: "Portfolio Manager",
          company: "Student",
          rating: 5,
          imageSrc: "http://img.b2bpic.net/free-photo/business-composition-with-modern-style_23-2147900149.jpg",
        },
      ]}
      kpiItems={[
        {
          value: "4.9/5",
          label: "Average Rating",
        },
        {
          value: "1.2k",
          label: "Active Traders",
        },
        {
          value: "98%",
          label: "Learner Satisfaction",
        },
      ]}
      title="Student Success Stories"
      description="What our students say about the ADG experience."
    />
  </div>

  <div id="faq" data-section="faq">
      <FaqDouble
      textboxLayout="default"
      useInvertedBackground={false}
      faqs={[
        {
          id: "f1",
          title: "Is trading risky?",
          content: "Yes, trading involves significant risk of loss. Demo accounts help you practice without real financial risk.",
        },
        {
          id: "f2",
          title: "Do I get a real account?",
          content: "No, our accounts are strictly for educational and demo purposes.",
        },
        {
          id: "f3",
          title: "How do I sign up?",
          content: "Fill out the contact form below and a representative will guide you through the process.",
        },
      ]}
      title="Frequently Asked Questions"
      description="Common questions regarding our education and demo accounts."
      faqsAnimation="slide-up"
    />
  </div>

  <div id="contact" data-section="contact">
      <ContactCenter
      useInvertedBackground={true}
      background={{
        variant: "sparkles-gradient",
      }}
      title="Start Your Journey Today"
      description="Submit your request to create a demo account. Our team will contact you shortly."
      termsText="I understand the risks involved with trading and agree to proceed responsibly."
    />
  </div>

  <div id="footer" data-section="footer">
      <FooterBaseReveal
      logoText="ADG Trading Center"
      columns={[
        {
          title: "Navigation",
          items: [
            {
              label: "Home",
              href: "#hero",
            },
            {
              label: "About",
              href: "#about",
            },
            {
              label: "Pricing",
              href: "#pricing",
            },
          ],
        },
        {
          title: "Legal",
          items: [
            {
              label: "Terms & Conditions",
              href: "#",
            },
            {
              label: "Privacy Policy",
              href: "#",
            },
            {
              label: "Risk Disclaimer",
              href: "#",
            },
          ],
        },
        {
          title: "Connect",
          items: [
            {
              label: "Discord",
              href: "#",
            },
            {
              label: "Telegram",
              href: "#",
            },
          ],
        },
      ]}
      copyrightText="© 2026 ADG Trading Center. All Rights Reserved."
    />
  </div>
      </ReactLenis>
    </ThemeProvider>
  );
}
